//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItems()
        {
            this.OrderMenuItems1 = new HashSet<OrderMenuItems>();
        }
    
        public int MenuItemId { get; set; }
        public string MenuItemName { get; set; }
        public int Calories { get; set; }
        public int Price { get; set; }
        public int MenuId { get; set; }
        public Nullable<int> OrderMenuItem_OrderMenuItemId { get; set; }
    
        public virtual Menus Menus { get; set; }
        public virtual OrderMenuItems OrderMenuItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMenuItems> OrderMenuItems1 { get; set; }
    }
}
